name: classfrase_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  # sdk: '>=2.19.6 <3.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter      
  # Gerenciador de estados
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  # Back4app
  # parse_server_sdk_flutter: ^4.0.0
  parse_server_sdk_flutter:
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: master
      path: packages/flutter/

  # pdf
  pdf: ^3.10.1
  printing: ^5.10.3
    # image
  image_picker: ^0.8.6+2
  image_picker_for_web: ^2.1.10
  # outros
  validatorless: ^1.2.3
  intl: ^0.18.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  flutter_simple_treeview: ^3.0.2
  collection: ^1.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
